### ISSUE TITLE
Support `@returns`

### ISSUE THREAD

**Issue by dipterix** [ThinkR-open/checkhelper#81]
Currently `find_missing_tags` checks `@return`, but it seems the new roxygen2 encourage people to use `@returns`

**Comment by statnmap** [comment]
Thanks. We'll see what we can do.  
_If you want to implement the fix with a PR, we can guide you through the process_

More info:  
roxygen2 7.0.0: *  New `@returns` is an alias for `@return` (#952) - https://github.com/r-lib/roxygen2/blob/a34bdf7c7b952068b1f7742b7b34d1eac78e54da/NEWS.md?plain=1#L314

```yaml
- name: return
  description: >
    Describe the function's output. Superseded in favour of `@returns`.
  template: ' ${1:description}'
  vignette: rd
```
https://github.com/r-lib/roxygen2/blob/a34bdf7c7b952068b1f7742b7b34d1eac78e54da/inst/roxygen2-tags.yml#L335
